# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera

PRODUCT_COPY_FILES += \
    vendor/xiaomi/miuicamera/proprietary/system/etc/default-permissions/miuicamera-permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/miuicamera-permissions.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/permissions/privapp-permissions-miuicamera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-miuicamera.xml \
    vendor/xiaomi/miuicamera/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt \
    vendor/xiaomi/miuicamera/proprietary/system/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/miuicamera-hiddenapi-package-whitelist.xml

PRODUCT_PACKAGES += \
    android.hardware.camera.common_1.0 \
    libMNN \
    libarcsoft_single_chart_calibration \
    libauto_crop_c++_shared \
    libautocrop \
    libcommon \
    libdoc_photo_process \
    libgallery_arcsoft_dualcam_refocus \
    libgallery_arcsoft_portrait_lighting \
    libgallery_arcsoft_portrait_lighting_c \
    libgallery_mpbase \
    libmegvii_bokeh_jni \
    libmialgo_ai_vision \
    libmialgo_autocrop \
    libmialgo_portrait \
    libmialgo_utils_extraphoto \
    libmibrain_relighting_jni \
    libmicamera_dual_bokeh_jni \
    libmiocr_wrapper \
    libmiphone_bokeh_dynSpot \
    libmiphone_bokeh_effect \
    libmiphone_bokeh_gpf \
    libmiphone_bokeh_proc \
    libmiphone_refocus_bokeh \
    libmiuiblursdk \
    librefocus \
    librefocus_meitu \
    librefocus_mibokeh \
    libselection \
    libwa_refocus_extraphoto \
    libxcrash \
    libxcrash_dumper \
    vendor.qti.hardware.camera.device@1.0 \
    MiuiCamera \
    MiuiExtraPhoto \
    MiuiScanner
